pull_request_rules:
  - name: template-leak-test
    conditions:
      - base=main
    actions:
      comment:
        message: |
          Author: {{ author }}
          Title: {{ title }}
          Lipsum: {{ lipsum }}
          Cycler: {{ cycler }}
          Namespace: {{ namespace }}
          Range: {{ range }}
          Dict: {{ dict }}
